// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jebbjrmtzmovxubjcdki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplYmJqcm10em1vdnh1YmpjZGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzIzMzcsImV4cCI6MjA1MTIwODMzN30.aOxeQUg88mIpI-_m7XSpJV26rAiyADzuV-x_W9eg5HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);